[package]
name = "patchwork"
version = "0.1.0"
authors = ["Thomas Nguyen <thomas.nguyen.1197@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
uuid = { version = "0.8", features = ["v4"] }
